export const countries = [
    {label: 'Afganistán', value: 'AFGANISTAN'},
    {label: 'Albania', value: 'ALBANIA'},
    {label: 'Alemania', value: 'ALEMANIA'},
    {label: 'Andorra', value: 'ANDORRA'},
    {label: 'Angola', value: 'ANGOLA'},
    {label: 'Antigua y Barbuda', value: 'ANTIGUA Y BARBUDA'},
    {label: 'Arabia Saudita', value: 'ARABIA SAUDITA'},
    {label: 'Argelia', value: 'ARGELIA'},
    {label: 'Argentina', value: 'ARGENTINA'},
    {label: 'Armenia', value: 'ARMENIA'},
    {label: 'Australia', value: 'AUSTRALIA'},
    {label: 'Austria', value: 'AUSTRIA'},
    {label: 'Azerbaiyán', value: 'AZERBAIYAN'},
    {label: 'Bahamas', value: 'BAHAMAS'},
    {label: 'Bangladés', value: 'BANGLADES'},
    {label: 'Barbados', value: 'BARBADOS'},
    {label: 'Baréin', value: 'BAREIN'},
    {label: 'Belgica', value: 'BELGICA'},
    {label: 'Belice', value: 'BELICE'},
    {label: 'Benín', value: 'BENIN'},
    {label: 'Bielorrusia', value: 'BIELORRUSIA'},
    {label: 'Birmania', value: 'BIRMANIA'},
    {label: 'Bolivia', value: 'BOLIVIA'},
    {label: 'Bosnia y Herzegovina', value: 'BOSNIA Y HERZEGOVINA'},
    {label: 'Botsuana', value: 'BOTSUANA'},
    {label: 'Brasil', value: 'BRASIL'},
    {label: 'Brunéi', value: 'BRUNEI'},
    {label: 'Bulgaria', value: 'BULGARIA'},
    {label: 'Burkina Faso', value: 'BURKINA FASO'},
    {label: 'Burundi', value: 'BURUNDI'},
    {label: 'Bután', value: 'BUTAN'},
    {label: 'Cabo Verde', value: 'CABO VERDE'},
    {label: 'Camboya', value: 'CAMBOYA'},
    {label: 'Camerún', value: 'CAMERUN'},
    {label: 'Canadá', value: 'CANADA'},
    {label: 'Catar', value: 'CATAR'},
    {label: 'Chad', value: 'CHAD'},
    {label: 'Chile', value: 'CHILE'},
    {label: 'China', value: 'CHINA'},
    {label: 'Chipre', value: 'CHIPRE'},
    {label: 'Ciudad del Vaticano', value: 'CIUDAD DEL VATICANO'},
    {label: 'Colombia', value: 'COLOMBIA'},
    {label: 'Comoras', value: 'COMORAS'},
    {label: 'Corea del Norte', value: 'COREA DEL NORTE'},
    {label: 'Corea del Sur', value: 'COREA DEL SUR'},
    {label: 'Costa de Marfil', value: 'COSTA DE MARFIL'},
    {label: 'Costa Rica', value: 'COSTA RICA'},
    {label: 'Croacia', value: 'CROACIA'},
    {label: 'Cuba', value: 'CUBA'},
    {label: 'Dinamarca', value: 'DINAMARCA'},
    {label: 'Dominica', value: 'DOMINICA'},
    {label: 'Ecuador', value: 'ECUADOR'},
    {label: 'Egipto', value: 'EGIPTO'},
    {label: 'El Salvador', value: 'EL SALVADOR'},
    {label: 'Emiratos Árabes Unidos', value: 'EMIRATOS ARABES UNIDOS'},
    {label: 'Eritrea', value: 'ERITREA'},
    {label: 'Eslovaquia', value: 'ESLOVAQUIA'},
    {label: 'Eslovenia', value: 'ESLOVENIA'},
    {label: 'España', value: 'ESPANA'},
    {label: 'Estados Unidos', value: 'ESTADOS UNIDOS'},
    {label: 'Estonia', value: 'ESTONIA'},
    {label: 'Etiopía', value: 'ETIOPIA'},
    {label: 'Filipinas', value: 'FILIPINAS'},
    {label: 'Finlandia', value: 'FINLANDIA'},
    {label: 'Fiyi', value: 'FIYI'},
    {label: 'Francia', value: 'FRANCIA'},
    {label: 'Gabón', value: 'GABON'},
    {label: 'Gambia', value: 'GAMBIA'},
    {label: 'Georgia', value: 'GEORGIA'},
    {label: 'Ghana', value: 'GHANA'},
    {label: 'Granada', value: 'GRANADA'},
    {label: 'Grecia', value: 'GRECIA'},
    {label: 'Guatemala', value: 'GUATEMALA'},
    {label: 'Guyana', value: 'GUYANA'},
    {label: 'Guinea', value: 'GUINEA'},
    {label: 'Guinea ecuatorial', value: 'GUINEA ECUATORIAL'},
    {label: 'Guinea-Bisáu', value: 'GUINEA-BISAU'},
    {label: 'Haití', value: 'HAITI'},
    {label: 'Honduras', value: 'HONDURAS'},
    {label: 'Hungría', value: 'HUNGRIA'},
    {label: 'India', value: 'INDIA'},
    {label: 'Indonesia', value: 'INDONESIA'},
    {label: 'Irak', value: 'IRAK'},
    {label: 'Irán', value: 'IRAN'},
    {label: 'Irlanda', value: 'IRLANDA'},
    {label: 'Islandia', value: 'ISLANDIA'},
    {label: 'Islas Marshall', value: 'ISLAS MARSHALL'},
    {label: 'Islas Salomón', value: 'ISLAS SALOMON'},
    {label: 'Israel', value: 'ISRAEL'},
    {label: 'Italia', value: 'ITALIA'},
    {label: 'Jamaica', value: 'JAMAICA'},
    {label: 'Japón', value: 'JAPON'},
    {label: 'Jordania', value: 'JORDANIA'},
    {label: 'Kazajistán', value: 'KAZAJISTAN'},
    {label: 'Kenia', value: 'KENIA'},
    {label: 'Kirguistán', value: 'KIRGUISTAN'},
    {label: 'Kiribati', value: 'KIRIBATI'},
    {label: 'Kuwait', value: 'KUWAIT'},
    {label: 'Laos', value: 'LAOS'},
    {label: 'Lesoto', value: 'LESOTO'},
    {label: 'Letonia', value: 'LETONIA'},
    {label: 'Libano', value: 'LIBANO'},
    {label: 'Liberia', value: 'LIBERIA'},
    {label: 'Libia', value: 'LIBIA'},
    {label: 'Liechtenstein', value: 'LIECHTENSTEIN'},
    {label: 'Lituania', value: 'LITUANIA'},
    {label: 'Luxemburgo', value: 'LUXEMBURGO'},
    {label: 'Macedonia del Norte', value: 'MACEDONIA DEL NORTE'},
    {label: 'Madagascar', value: 'MADAGASCAR'},
    {label: 'Malasia', value: 'MALASIA'},
    {label: 'Malaui', value: 'MALAUI'},
    {label: 'Maldivas', value: 'MALDIVAS'},
    {label: 'Malta', value: 'MALTA'},
    {label: 'Marruecos', value: 'MARRUECOS'},
    {label: 'Mauricio', value: 'MAURICIO'},
    {label: 'Mauritania', value: 'MAURITANIA'},
    {label: 'Mexico', value: 'MEXICO'},
    {label: 'Micronesia', value: 'MICRONESIA'},
    {label: 'Moldavia', value: 'MOLDAVIA'},
    {label: 'Monaco', value: 'MONACO'},
    {label: 'Mongolia', value: 'MONGOLIA'},
    {label: 'Montenegro', value: 'MONTENEGRO'},
    {label: 'Mozambique', value: 'MOZAMBIQUE'},
    {label: 'Namibia', value: 'NAMIBIA'},
    {label: 'Nauru', value: 'NAURU'},
    {label: 'Nepal', value: 'NEPAL'},
    {label: 'Nicaragua', value: 'NICARAGUA'},
    {label: 'Niger', value: 'NIGER'},
    {label: 'Nigeria', value: 'NIGERIA'},
    {label: 'Noruega', value: 'NORUEGA'},
    {label: 'Nueva Zelanda', value: 'NUEVA ZELANDA'},
    {label: 'Omán', value: 'OMAN'},
    {label: 'Paises Bajos', value: 'PAISES BAJOS'},
    {label: 'Pakistán', value: 'PAKISTAN'},
    {label: 'Palaos', value: 'PALAOS'},
    {label: 'Panamá', value: 'PANAMA'},
    {label: 'Papúa Nueva Guinea', value: 'PAPUA NUEVA GUINEA'},
    {label: 'Paraguay', value: 'PARAGUAY'},
    {label: 'Perú', value: 'PERU'},
    {label: 'Polonia', value: 'POLONIA'},
    {label: 'Portugal', value: 'PORTUGAL'},
    {label: 'Puerto Rico', value: 'PUERTO RICO'},
    {label: 'Reino Unido', value: 'REINO UNIDO'},
    {label: 'Republica Centroafricana', value: 'REPUBLICA CENTROAFRICANA'},
    {label: 'Republica Checa', value: 'REPUBLICA CHECA'},
    {label: 'Republica del Congo', value: 'REPUBLICA DEL CONGO'},
    {label: 'Republica Democrática del Congo', value: 'REPUBLICA DEMOCRATICA DEL CONGO'},
    {label: 'Republica Dominicana', value: 'REPUBLICA DOMINICANA'},
    {label: 'Republica Sudafricana', value: 'REPUBLICA SUDAFRICANA'},
    {label: 'Ruanda', value: 'RUANDA'},
    {label: 'Rumanía', value: 'RUMANIA'},
    {label: 'Rusia', value: 'RUSIA'},
    {label: 'Samoa', value: 'SAMOA'},
    {label: 'San Cristóbal y Nieves', value: 'SAN CRISTOBAL Y NIEVES'},
    {label: 'San Marino', value: 'SAN MARINO'},
    {label: 'San Vicente y las Granadinas', value: 'SAN VICENTE Y LAS GRANADINAS'},
    {label: 'Santa Lucía', value: 'SANTA LUCIA'},
    {label: 'Santo Tomé y Príncipe', value: 'SANTO TOME Y PRINCIPE'},
    {label: 'Senegal', value: 'SENEGAL'},
    {label: 'Serbia', value: 'SERBIA'},
    {label: 'Seychelles', value: 'SEYCHELLES'},
    {label: 'Sierra Leona', value: 'SIERRA LEONA'},
    {label: 'Singapur', value: 'SINGAPUR'},
    {label: 'Siria', value: 'SIRIA'},
    {label: 'Somalia', value: 'SOMALIA'},
    {label: 'Sri Lanka', value: 'SRI LANKA'},
    {label: 'Suazilandia', value: 'SUAZILANDIA'},
    {label: 'Sudán', value: 'SUDAN'},
    {label: 'Sudán del Sur', value: 'SUDAN DEL SUR'},
    {label: 'Suecia', value: 'SUECIA'},
    {label: 'Suiza', value: 'SUIZA'},
    {label: 'Surinam', value: 'SURINAM'},
    {label: 'Tailandia', value: 'TAILANDIA'},
    {label: 'Tanzania', value: 'TANZANIA'},
    {label: 'Tayikistán', value: 'TAYIKISTAN'},
    {label: 'Timor Oriental', value: 'TIMOR ORIENTAL'},
    {label: 'Togo', value: 'TOGO'},
    {label: 'Tonga', value: 'TONGA'},
    {label: 'Trinidad y Tobago', value: 'TRINIDAD Y TOBAGO'},
    {label: 'Tunez', value: 'TUNEZ'},
    {label: 'Turkmenistán', value: 'TURKMENISTAN'},
    {label: 'Turquía', value: 'TURQUIA'},
    {label: 'Tuvalu', value: 'TUVALU'},
    {label: 'Ucrania', value: 'UCRANIA'},
    {label: 'Uganda', value: 'UGANDA'},
    {label: 'Uruguay', value: 'URUGUAY'},
    {label: 'Uzbekistán', value: 'UZBEKISTAN'},
    {label: 'Vanuatu', value: 'VANUATU'},
    {label: 'Venezuela', value: 'VENEZUELA'},
    {label: 'Vietnam', value: 'VIETNAM'},
    {label: 'Yemen', value: 'YEMEN'},
    {label: 'Yibuti', value: 'YIBUTI'},
    {label: 'Zambia', value: 'ZAMBIA'},
    {label: 'Zimbabue', value: 'ZIMBABUE'}
];
